name: Events api CI

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Set up JDK 22 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven # Stores dependencies to speed up your workflow executions
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
